help:
	hatch run dev:help

lint:
	hatch run dev:lint

mkdocs:
	hatch run dev:mkdocs

build_doc:
	hatch run dev:build_doc

pre_commit:
	hatch run dev:pre_commit

hello_world:
	hatch run dev:hello_world
